# Generated by Django 4.1.1 on 2023-06-01 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medicalType',
            field=models.TextField(choices=[('Lab', 'Lab'), ('Hospital', 'Hospital'), ('Petiant', 'Petiant'), ('Clinic', 'Clinic')], default='Petiant'),
        ),
    ]
