# Generated by Django 4.1.1 on 2023-06-01 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0003_alter_profile_medicaltype_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(upload_to='photo/profilePic'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medicalType',
            field=models.TextField(choices=[('Lab', 'Lab'), ('Hospital', 'Hospital'), ('Petiant', 'Petiant'), ('Clinic', 'Clinic')], default='Petiant'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationalID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='clinicPICs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='photo/clincPic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_app.doctor')),
            ],
        ),
    ]
