# Generated by Django 4.1.1 on 2023-06-01 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0005_alter_clinicpics_pic_alter_profile_medicaltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='reception',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_app.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medicalType',
            field=models.TextField(choices=[('Petiant', 'Petiant'), ('Hospital', 'Hospital'), ('Clinic', 'Clinic'), ('Lab', 'Lab')], default='Petiant'),
        ),
    ]
