# Generated by Django 4.1.1 on 2023-06-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0006_alter_doctor_reception_alter_profile_medicaltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medicalType',
            field=models.TextField(choices=[('Lab', 'Lab'), ('Clinic', 'Clinic'), ('Petiant', 'Petiant'), ('Hospital', 'Hospital')], default='Petiant'),
        ),
    ]
