# Generated by Django 4.1.1 on 2023-06-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0007_doctor_slug_alter_profile_medicaltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medicalType',
            field=models.TextField(choices=[('Clinic', 'Clinic'), ('Lab', 'Lab'), ('Hospital', 'Hospital'), ('Petiant', 'Petiant')], default='Petiant'),
        ),
    ]
