# Generated by Django 4.1.1 on 2023-06-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0008_alter_doctor_slug_alter_profile_medicaltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.TextField(blank=True, choices=[('male', 'male'), ('female', 'female')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medicalType',
            field=models.TextField(choices=[('Petiant', 'Petiant'), ('Hospital', 'Hospital'), ('Lab', 'Lab'), ('Clinic', 'Clinic')], default='Petiant'),
        ),
    ]
