# Generated by Django 4.1.1 on 2023-06-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0009_alter_doctor_gender_alter_profile_medicaltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.TextField(blank=True, choices=[('female', 'female'), ('male', 'male')], null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialist',
            field=models.TextField(blank=True, choices=[('Counselor', 'Counselor'), ('eras && nose', 'eras && nose'), ('heart', 'heart')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medicalType',
            field=models.TextField(choices=[('Hospital', 'Hospital'), ('Clinic', 'Clinic'), ('Lab', 'Lab'), ('Petiant', 'Petiant')], default='Petiant'),
        ),
    ]
